plugins {
    alias libs.plugins.fabric.loom

    alias libs.plugins.oro.general.gradle.plugin
    alias libs.plugins.oro.minecraft.gradle.plugin
}

version = project.mod_version
group = project.maven_group

repositories {
    maven {
        name = "OroArmor"
        url = "https://maven.oroarmor.com"
    }
    maven {
        name = "Jitpack"
        url = 'https://jitpack.io'
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/releases/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven { url 'https://repo.sleeping.town/' }
}

oroarmor {
    name = "Netherite-Plus-Mod"
    githubProjectName = "OroArmorModding/Netherite-Plus-Mod"
    description = "This mod adds extra netherite features that aren't vanilla.\n\nNOTE: Editing the config requires a game restart."

    println(projectPublishing.changelog.get())
}

import com.oroarmor.orogradleplugin.minecraft.dependency.ModDependency.DependencyType
minecraftPublishing {
    gameVersions = [libs.versions.minecraft.get()]
    modrinthId = "MlaM22M4"
    curseforgeId = "394120"
    releaseType = ReleaseType.BETA
    dependencies {
        "ranged-weapon-api" {
            version = libs.versions.ranged.weapon.api.get()
            type = DependencyType.REQUIRED
        }
        "fabric-api" {
            version = libs.versions.fabric.api.get()
            type = DependencyType.REQUIRED
        }
    }
    loaders = ["Fabric"]
    modTask = jar
}

license {
    exclude '**/*.accesswidener'
    exclude '**/.cache/*'
}

loom {
    accessWidenerPath = file("src/main/resources/netherite_plus.accesswidener")

    splitEnvironmentSourceSets()
}

fabricApi {
    configureDataGeneration() {
        client = true
        strictValidation = true
        createRunConfiguration = true
        createSourceSet = true
        modId = "netherite_plus"
        outputDirectory = file("src/datagen/resources")
    }
}

dependencies {
    minecraft libs.minecraft
    implementation libs.fabric.loader

    implementation libs.fabric.api

    implementation libs.kaleido.config
    include libs.kaleido.config

    implementation libs.ranged.weapon.api
}

processResources {
    inputs.property "version", version

    filesMatching('fabric.mod.json') {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25

    withSourcesJar()
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_${project.name}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            oroarmor.generateDefaultPom(it)
        }
    }

    repositories {
        mavenLocal()
    }
}

import net.fabricmc.loom.task.ValidateMixinNameTask
tasks.register('validateMixinNames', ValidateMixinNameTask) {
    source(sourceSets.main.output)
    source(sourceSets.client.output)
}

check.dependsOn "validateMixinNames"

import com.oroarmor.orogradleplugin.publish.PublishProjectToGithubTask
tasks.register("github", PublishProjectToGithubTask) {
    assets.from(jar, sourcesJar)
}

import com.oroarmor.orogradleplugin.minecraft.*
tasks.register("curseforge", CurseforgePublishTask)
tasks.register("modrinth", ModrinthPublishTask)
