# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Quilt Properties
minecraft_version=26.3
fabric_loader_version=0.19.5

# Mod Properties
mod_version=3.0.0-beta.1
maven_group=com.oroarmor
archives_base_name=netherite-plus-mod
project_name=Netherite Plus Mod
discord_hook_image_url=https://raw.githubusercontent.com/OroArmorModding/Netherite-Plus-Mod/742eaf744ad79946d47ddc7b070ddbc90b05bb03/src/main/resources/assets/netherite_plus/icon.png

# Dependencies
fabric_api_version=0.161.0+26.3
kaleido_config_version = 0.3.3+1.3.2
ranged_weapon_api_version = 4.0.0+26.3-fabric
