# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Mod Properties
mod_version=3.0.0-beta.1
maven_group=com.oroarmor
project_name=Netherite Plus Mod
discord_hook_image_url=https://raw.githubusercontent.com/OroArmorModding/Netherite-Plus-Mod/742eaf744ad79946d47ddc7b070ddbc90b05bb03/src/main/resources/assets/netherite_plus/icon.png